export const heILCustom = {
  socialButtonsBlockButton: "המשך עם {{provider|titleize}}",
  dividerText: "או",
  formFieldLabel__emailAddress: "כתובת אימייל",
  formFieldLabel__emailAddress_username: "אימייל או שם משתמש",
  formFieldLabel__password: "סיסמה",
  formFieldLabel__firstName: "שם פרטי",
  formFieldLabel__lastName: "שם משפחה",
  formFieldLabel__username: "שם משתמש",
  formFieldLabel__phoneNumber: "מספר טלפון",
  formFieldLabel__confirmPassword: "אימות סיסמה",
  formFieldLabel__newPassword: "סיסמה חדשה",
  formFieldLabel__currentPassword: "סיסמה נוכחית",
  formFieldLabel__organizationName: "שם הארגון",
  formFieldLabel__organizationSlug: "כתובת הארגון",
  formFieldLabel__role: "תפקיד",
  formFieldLabel__signOutOfOtherSessions: "התנתק מכל המכשירים האחרים",
  formFieldInputPlaceholder__emailAddress: "הזן כתובת אימייל",
  formFieldInputPlaceholder__emailAddress_username: "הזן אימייל או שם משתמש",
  formFieldInputPlaceholder__password: "הזן סיסמה",
  formFieldInputPlaceholder__firstName: "הזן שם פרטי",
  formFieldInputPlaceholder__lastName: "הזן שם משפחה",
  formFieldInputPlaceholder__username: "הזן שם משתמש",
  formFieldInputPlaceholder__phoneNumber: "הזן מספר טלפון",
  formFieldInputPlaceholder__organizationName: "הזן שם ארגון",
  formFieldInputPlaceholder__organizationSlug: "הזן כתובת ארגון",
  formFieldAction__forgotPassword: "שכחת סיסמה?",
  formButtonPrimary: "המשך",
  formButtonPrimary__verify: "אמת",
  formButtonReset: "ביטול",
  footerActionLink__useAnotherMethod: "השתמש בשיטה אחרת",
  backButton: "חזור",
  signIn: {
    start: {
      title: "התחברות",
      subtitle: "ברוכים הבאים! התחבר כדי להמשיך",
      actionText: "אין לך חשבון?",
      actionLink: "הרשם",
    },
    password: {
      title: "הזן סיסמה",
      subtitle: "הזן את הסיסמה המשויכת לחשבון שלך",
      actionLink: "שימוש בשיטה אחרת",
    },
    forgotPasswordAlternativeMethods: {
      title: "שכחת סיסמה?",
      label__alternativeMethods: "או, התחבר בשיטה אחרת",
      blockButton__resetPassword: "אפס סיסמה",
    },
    emailCode: {
      title: "בדוק את האימייל",
      subtitle: "כדי להמשיך אל {{applicationName}}",
      formTitle: "קוד אימות",
      formSubtitle: "הזן את קוד האימות שנשלח לכתובת האימייל שלך",
      resendButton: "שלח קוד מחדש",
    },
  },
  signUp: {
    start: {
      title: "הרשמה",
      subtitle: "ברוכים הבאים! מלא את הפרטים כדי להתחיל",
      actionText: "יש לך חשבון?",
      actionLink: "התחבר",
    },
    emailCode: {
      title: "אמת את האימייל",
      subtitle: "הזן את קוד האימות שנשלח לאימייל שלך",
      formTitle: "קוד אימות",
      formSubtitle: "הזן את קוד האימות שנשלח לכתובת האימייל שלך",
      resendButton: "שלח קוד מחדש",
    },
    continue: {
      title: "מלא פרטים חסרים",
      subtitle: "מלא את הפרטים הנותרים כדי להמשיך",
      actionText: "יש לך חשבון?",
      actionLink: "התחבר",
    },
  },
  userButton: {
    action__manageAccount: "ניהול חשבון",
    action__signOut: "התנתק",
    action__signOutAll: "התנתק מכל החשבונות",
    action__addAccount: "הוסף חשבון",
  },
  userProfile: {
    start: {
      headerTitle__account: "חשבון",
      headerTitle__security: "אבטחה",
      headerSubtitle__account: "ניהול פרטי החשבון",
      headerSubtitle__security: "ניהול הגדרות אבטחה",
      profileSection: {
        title: "פרופיל",
        primaryButton: "עדכן פרופיל",
      },
      usernameSection: {
        title: "שם משתמש",
        primaryButton: "עדכן שם משתמש",
      },
      emailAddressesSection: {
        title: "כתובות אימייל",
        primaryButton: "הוסף כתובת אימייל",
        detailsTitle__primary: "כתובת ראשית",
        detailsSubtitle__primary: "כתובת זו היא כתובת האימייל הראשית",
        detailsAction__primary: "השלם אימות",
        detailsAction__nonPrimary: "הגדר כראשית",
        detailsAction__unverified: "אמת כתובת אימייל",
        destructiveAction: "הסר אימייל",
      },
      phoneNumbersSection: {
        title: "מספרי טלפון",
        primaryButton: "הוסף מספר טלפון",
        detailsTitle__primary: "מספר ראשי",
        detailsSubtitle__primary: "מספר זה הוא המספר הראשי",
        destructiveAction: "הסר מספר טלפון",
      },
      connectedAccountsSection: {
        title: "חשבונות מקושרים",
        primaryButton: "קשר חשבון",
        actionLabel__connectionFailed: "נסה שוב",
        actionLabel__reauthorize: "אשר מחדש",
        destructiveActionTitle: "הסר",
      },
      dangerSection: {
        title: "מחיקת חשבון",
        deleteAccountButton: "מחק חשבון",
      },
      activeDevicesSection: {
        title: "מכשירים פעילים",
        destructiveAction: "התנתק ממכשיר",
      },
      passwordSection: {
        title: "סיסמה",
        primaryButton__changePassword: "שנה סיסמה",
        primaryButton__setPassword: "הגדר סיסמה",
      },
      mfaSection: {
        title: "אימות דו-שלבי",
        primaryButton: "הוסף אימות דו-שלבי",
      },
    },
    navbar: {
      title: "חשבון",
      description: "ניהול פרטי החשבון",
      account: "פרופיל",
      security: "אבטחה",
    },
    profileSection: {
      title: "פרופיל",
      primaryButton: "עדכן פרופיל",
    },
    usernameSection: {
      title: "שם משתמש",
      primaryButton: "עדכן שם משתמש",
      primaryButton__changeUsername: "שנה שם משתמש",
      primaryButton__setUsername: "הגדר שם משתמש",
    },
    emailAddressesSection: {
      title: "כתובות אימייל",
      primaryButton: "הוסף כתובת אימייל",
      detailsTitle__primary: "כתובת ראשית",
      detailsSubtitle__primary: "כתובת זו היא כתובת האימייל הראשית",
      detailsAction__primary: "השלם אימות",
      detailsAction__nonPrimary: "הגדר כראשית",
      detailsAction__unverified: "אמת כתובת אימייל",
      destructiveAction: "הסר אימייל",
    },
    phoneNumbersSection: {
      title: "מספרי טלפון",
      primaryButton: "הוסף מספר טלפון",
      detailsTitle__primary: "מספר ראשי",
      detailsSubtitle__primary: "מספר זה הוא המספר הראשי",
      destructiveAction: "הסר מספר טלפון",
    },
    connectedAccountsSection: {
      title: "חשבונות מקושרים",
      primaryButton: "קשר חשבון",
      actionLabel__connectionFailed: "נסה שוב",
      actionLabel__reauthorize: "אשר מחדש",
      destructiveActionTitle: "הסר",
    },
    activeDevicesSection: {
      title: "מכשירים פעילים",
      primaryButton: "מכשירים פעילים",
      detailsTitle: "מכשיר נוכחי",
      destructiveActionTitle: "התנתק",
      destructiveAction: "התנתק ממכשיר",
    },
    passwordSection: {
      title: "סיסמה",
      primaryButton__changePassword: "שנה סיסמה",
      primaryButton__setPassword: "הגדר סיסמה",
    },
    mfaSection: {
      title: "אימות דו-שלבי",
      primaryButton: "הוסף אימות דו-שלבי",
    },
    dangerSection: {
      title: "מחיקת חשבון",
      deleteAccountButton: "מחק חשבון",
    },
    profilePage: {
      title: "עדכן פרופיל",
      imageFormTitle: "תמונת פרופיל",
      imageFormSubtitle: "העלה תמונה",
      imageFormDestructiveActionSubtitle: "הסר תמונה",
      fileDropAreaTitle: "גרור קובץ לכאן, או...",
      fileDropAreaAction: "בחר קובץ",
      fileDropAreaHint: "גודל מומלץ 1:1, עד 10MB",
      successMessage: "הפרופיל שלך עודכן",
      readonly: "פרטי הפרופיל שלך סופקו על ידי חיבור הארגון ולא ניתנים לעריכה.",
    },
    usernamePage: {
      title: "עדכן שם משתמש",
      successMessage: "שם המשתמש שלך עודכן",
    },
    emailAddressPage: {
      title: "הוסף כתובת אימייל",
      formHint: "הזן כתובת אימייל להוספה",
      emailCode: {
        formTitle: "קוד אימות",
        formSubtitle: "הזן את קוד האימות שנשלח ל-{{identifier}}",
        resendButton: "שלח קוד מחדש",
        successMessage: "האימייל {{identifier}} נוסף לחשבון שלך",
      },
    },
    connectedAccountPage: {
      title: "הוסף חשבון מקושר",
      formHint: "בחר ספק לקישור החשבון",
      socialButtonsBlockButton: "קשר חשבון {{provider|titleize}}",
      successMessage: "הספק נוסף לחשבון שלך",
      removeResource: {
        title: "הסר חשבון מקושר",
        messageLine1: "{{identifier}} יוסר מהחשבון שלך",
        messageLine2: "לא תוכל להשתמש בחשבון מקושר זה יותר",
        successMessage: "{{connectedAccount}} הוסר מהחשבון שלך",
      },
    },
    passwordPage: {
      title: "הגדר סיסמה",
      changePasswordTitle: "שנה סיסמה",
      successMessage: "הסיסמה עודכנה בהצלחה",
      changePasswordSuccessMessage: "הסיסמה שלך עודכנה",
      sessionsSignedOutSuccessMessage: "כל המכשירים האחרים התנתקו",
    },
    mfaPage: {
      title: "הוסף אימות דו-שלבי",
      formHint: "בחר שיטה להוספה",
    },
    mfaTOTPPage: {
      title: "הוסף אפליקציית אימות",
      verifyTitle: "קוד אימות",
      verifySubtitle: "הזן את קוד האימות שנוצר על ידי אפליקציית האימות שלך",
      successMessage: "אימות דו-שלבי מופעל כעת",
      authenticatorApp: {
        infoText: "הגדר אפליקציית אימות כדי ליצור קודי אימות",
        inputLabel: "קוד אימות",
        buttonAbleToScan__nonPrimary: "סרוק קוד QR במקום",
        buttonUnableToScan__nonPrimary: "לא מצליח לסרוק? הזן מפתח ידנית",
      },
    },
    deletePage: {
      title: "מחק חשבון",
      messageLine1: "האם אתה בטוח שברצונך למחוק את החשבון?",
      messageLine2: "פעולה זו היא לצמיתות ולא ניתנת לביטול",
      actionDescription: 'הקלד "מחק חשבון" למטה כדי להמשיך',
      confirm: "מחק חשבון",
    },
  },
  organizationSwitcher: {
    title: "בחר ארגון",
    subtitle: "עבור לארגון אחר",
    action__createOrganization: "צור ארגון",
    action__manageOrganization: "נהל ארגון",
    action__invitationAccept: "הצטרף",
    notSelected: "לא נבחר ארגון",
    personalWorkspace: "חשבון אישי",
  },
  organizationProfile: {
    start: {
      headerTitle__members: "חברים",
      headerTitle__settings: "הגדרות",
    },
    membersPage: {
      headerTitle__members: "חברים",
      headerTitle__invitations: "הזמנות",
      action__invite: "הזמן",
    },
  },
  createOrganization: {
    title: "צור ארגון",
    formButtonSubmit: "צור ארגון",
  },
  badge__primary: "ראשי",
  badge__thisDevice: "מכשיר זה",
  badge__userDevice: "מכשיר משתמש",
  badge__otherImpersonatorDevice: "מכשיר מתחזה",
  badge__default: "ברירת מחדל",
  badge__unverified: "לא מאומת",
  badge__requiresAction: "דרוש פעולה",
  badge__you: "אתה",
  footerPageLink__help: "עזרה",
  footerPageLink__privacy: "פרטיות",
  footerPageLink__terms: "תנאים",
  unstable__errors: {
    form_identifier_not_found: "החשבון לא נמצא. בדוק את הפרטים ונסה שוב.",
    form_password_incorrect: "סיסמה שגויה. נסה שוב.",
    form_password_pwned: "סיסמה זו נמצאה כפגיעה. נסה סיסמה אחרת.",
    form_password_not_strong_enough: "הסיסמה לא חזקה מספיק.",
    form_password_size_in_range: "הסיסמה חייבת להכיל בין {{min}} ל-{{max}} תווים.",
    form_param_nil: "שדה זה הוא חובה.",
    form_code_incorrect: "קוד שגוי. נסה שוב.",
    not_allowed_access: "אין לך הרשאה לגשת למשאב זה.",
    form_identifier_exists: "שם משתמש זה כבר בשימוש. נסה שם אחר.",
    form_username_invalid_character: "שם המשתמש מכיל תווים לא חוקיים.",
    form_username_invalid_length: "שם המשתמש חייב להיות בין {{min}} ל-{{max}} תווים.",
  },
}
