export const heILCustom = {
  socialButtonsBlockButton: "המשך עם {{provider|titleize}}",
  dividerText: "או",
  formFieldLabel__emailAddress: "כתובת אימייל",
  formFieldLabel__password: "סיסמה",
  formFieldLabel__firstName: "שם פרטי",
  formFieldLabel__lastName: "שם משפחה",
  formFieldLabel__username: "שם משתמש",
  formFieldLabel__phoneNumber: "מספר טלפון",
  formFieldLabel__confirmPassword: "אימות סיסמה",
  formFieldLabel__newPassword: "סיסמה חדשה",
  formFieldLabel__currentPassword: "סיסמה נוכחית",
  formFieldLabel__organizationName: "שם הארגון",
  formFieldLabel__organizationSlug: "כתובת הארגון",
  formFieldLabel__role: "תפקיד",
  formFieldInputPlaceholder__emailAddress: "הזן כתובת אימייל",
  formFieldInputPlaceholder__password: "הזן סיסמה",
  formFieldInputPlaceholder__firstName: "הזן שם פרטי",
  formFieldInputPlaceholder__lastName: "הזן שם משפחה",
  formFieldInputPlaceholder__username: "הזן שם משתמש",
  formFieldInputPlaceholder__phoneNumber: "הזן מספר טלפון",
  formFieldInputPlaceholder__organizationName: "הזן שם ארגון",
  formFieldInputPlaceholder__organizationSlug: "הזן כתובת ארגון",
  formButtonPrimary: "המשך",
  formButtonPrimary__verify: "אמת",
  signIn: {
    start: {
      title: "התחברות",
      subtitle: "ברוכים הבאים! התחבר כדי להמשיך",
      actionText: "אין לך חשבון?",
      actionLink: "הרשם",
    },
    password: {
      title: "הזן סיסמה",
      subtitle: "הזן את הסיסמה המשויכת לחשבון שלך",
      actionLink: "שימוש בשיטה אחרת",
    },
    forgotPasswordAlternativeMethods: {
      title: "שכחת סיסמה?",
      label__alternativeMethods: "או, התחבר בשיטה אחרת",
      blockButton__resetPassword: "אפס סיסמה",
    },
    emailCode: {
      title: "בדוק את האימייל",
      subtitle: "כדי להמשיך אל {{applicationName}}",
      formTitle: "קוד אימות",
      formSubtitle: "הזן את קוד האימות שנשלח לכתובת האימייל שלך",
      resendButton: "שלח קוד מחדש",
    },
  },
  signUp: {
    start: {
      title: "הרשמה",
      subtitle: "ברוכים הבאים! מלא את הפרטים כדי להתחיל",
      actionText: "יש לך חשבון?",
      actionLink: "התחבר",
    },
    emailCode: {
      title: "אמת את האימייל",
      subtitle: "הזן את קוד האימות שנשלח לאימייל שלך",
      formTitle: "קוד אימות",
      formSubtitle: "הזן את קוד האימות שנשלח לכתובת האימייל שלך",
      resendButton: "שלח קוד מחדש",
    },
    continue: {
      title: "מלא פרטים חסרים",
      subtitle: "מלא את הפרטים הנותרים כדי להמשיך",
      actionText: "יש לך חשבון?",
      actionLink: "התחבר",
    },
  },
  userButton: {
    action__manageAccount: "ניהול חשבון",
    action__signOut: "התנתק",
    action__signOutAll: "התנתק מכל החשבונות",
    action__addAccount: "הוסף חשבון",
  },
  userProfile: {
    start: {
      headerTitle__account: "חשבון",
      headerTitle__security: "אבטחה",
      headerSubtitle__account: "ניהול פרטי החשבון",
      headerSubtitle__security: "ניהול הגדרות אבטחה",
    },
    profileSection: {
      title: "פרופיל",
      primaryButton: "עדכן פרופיל",
    },
    emailAddressPage: {
      title: "הוסף כתובת אימייל",
      formHint: "הזן כתובת אימייל להוספה",
    },
    passwordPage: {
      title: "הגדר סיסמה",
      changePasswordTitle: "שנה סיסמה",
      successMessage: "הסיסמה עודכנה בהצלחה",
    },
  },
  organizationSwitcher: {
    title: "בחר ארגון",
    subtitle: "עבור לארגון אחר",
    action__createOrganization: "צור ארגון",
    action__manageOrganization: "נהל ארגון",
    action__invitationAccept: "הצטרף",
    notSelected: "לא נבחר ארגון",
    personalWorkspace: "חשבון אישי",
  },
  organizationProfile: {
    start: {
      headerTitle__members: "חברים",
      headerTitle__settings: "הגדרות",
    },
    membersPage: {
      headerTitle__members: "חברים",
      headerTitle__invitations: "הזמנות",
      action__invite: "הזמן",
    },
  },
  createOrganization: {
    title: "צור ארגון",
    formButtonSubmit: "צור ארגון",
  },
  footerActionLink__useAnotherMethod: "השתמש בשיטה אחרת",
  badge__primary: "ראשי",
  badge__thisDevice: "מכשיר זה",
  badge__userDevice: "מכשיר משתמש",
  badge__otherImpersonatorDevice: "מכשיר מתחזה",
  badge__default: "ברירת מחדל",
  badge__unverified: "לא מאומת",
  badge__requiresAction: "דרוש פעולה",
  badge__you: "אתה",
  footerPageLink__help: "עזרה",
  footerPageLink__privacy: "פרטיות",
  footerPageLink__terms: "תנאים",
  unstable__errors: {
    form_identifier_not_found: "החשבון לא נמצא. בדוק את הפרטים ונסה שוב.",
    form_password_incorrect: "סיסמה שגויה. נסה שוב.",
    form_password_pwned: "סיסמה זו נמצאה כפגיעה. נסה סיסמה אחרת.",
    form_password_not_strong_enough: "הסיסמה לא חזקה מספיק.",
    form_password_size_in_range: "הסיסמה חייבת להכיל בין {{min}} ל-{{max}} תווים.",
    form_param_nil: "שדה זה הוא חובה.",
    form_code_incorrect: "קוד שגוי. נסה שוב.",
    not_allowed_access: "אין לך הרשאה לגשת למשאב זה.",
    form_identifier_exists: "כתובת אימייל זו כבר בשימוש. נסה כתובת אחרת.",
  },
}
